models/book.py
class Book:
    def __init__(self, title: str, author: str, genre: str, checked_out: bool = False):
        self.title = title
        self.author = author
        self.genre = genre
        self.checked_out = checked_out
        self.accession_id = None

    def get_author_sortkey(self):
        names = self.author.split(None)
        return names[-1] + ', ' + " ".join(names[0:-1])

    def check_in(self):
        self.checked_out = False

    def check_out(self):
        self.checked_out = True

    def get_accession_id(self):
        return self.accession_id

    def update_accession_id(self, accession_id: int):
        self.accession_id = accession_id
    
    def remove_accession_id(self):
        self.accession_id = None

models/library.py
from models.book import Book

# The 'Global Object Pattern'.
# https://python-patterns.guide/python/module-globals/

# library: set[Book] = set()

class Library():
    def __init__(self, name):
        self.name = name
        self.books = []

    def find_unused_accession_id(self):
        if len(self.books) == 0:
            new_accession_id = 100
        else:
            new_accession_id = 1 + max([book.accession_id for book in self.books])
        return new_accession_id

    def add_new_book(self, new_book: Book):
        if new_book.accession_id is None:
            new_accession_id = self.find_unused_accession_id()
            new_book.update_accession_id(new_accession_id)
            self.books.append(new_book)

    def delete_book(self, book: Book):
        self.books.remove(book)
        book.remove_accession_id()

    def find_book_by_accession_id(self, accession_id: int):
        for book in self.books:
            if book.get_accession_id() == accession_id:
                return book
        return

    def count_books(self):
        return len(self.books)

    def get_all_books(self):
        return [*self.books]

library = Library("The CodeClan Library")

library.add_new_book(Book("Equal Rites", "Terry Pratchett", "fantasy", True))
library.add_new_book(Book("The Art Of Statistics", "David Spiegelhalter", "popular mathematics", True))
library.add_new_book(Book("Flatterland", "Ian Stewart", "popular mathematics"))
library.add_new_book(Book("Mother Tongue: The English Language", "Bill Bryson", "language & reference"))
library.add_new_book(Book("The Joy of Abstraction", "Eugenia Cheng", "popular mathematics", True))
library.add_new_book(Book("The Periodic Table", "Primo Levi", "fiction"))
library.add_new_book(Book("The Secret Agent", "Joseph Conrad", "fiction"))

app.py
from flask import Flask, render_template

from controllers.books import books

# App Factory Pattern: https://flask.palletsprojects.com/en/2.2.x/patterns/appfactories/
def create_app():
    app = Flask(__name__)

    # https://stackoverflow.com/questions/46944596/is-autoescape-default-in-jinja2-flask
    app.jinja_options["autoescape"] = lambda _: True

    @app.errorhandler(404)
    def page_not_found(e):
        return """<!DOCTYPE html>
<html>
<head><title>404 Not Found</title></head>
<body><p><img src="https://http.cat/404.jpg"></p></body>
</html>
"""

    @app.route("/")
    def index():
        return render_template("base.html.j2", title="Welcome")

    app.register_blueprint(books)

    return app

if __name__ == "__main__":
    app = create_app()
    # app.run(debug=True)
    app.run()

controllers/books.py
from flask import Blueprint, request, render_template, url_for, redirect

from models.book import Book
from models.library import library

# Blueprints! https://flask.palletsprojects.com/en/2.2.x/blueprints/
books = Blueprint("books", __name__)

# Flask automatically redirects /books to /books/ but not the other way around
# https://flask.palletsprojects.com/en/2.2.x/quickstart/#unique-urls-redirection-behavior
# Docs for defaults: https://flask.palletsprojects.com/en/2.2.x/api/#url-route-registrations
@books.route('/books/', defaults={'sort_type': 'accession_id'})
@books.route('/books/sorted/<sort_type>')
def books_list(sort_type):
    key_func = lambda x: x # identity function
    match sort_type:
        case 'accession_id':
            key_func = lambda book: book.accession_id
        case 'title':
            key_func = lambda book: book.title
        case 'author':
            # so this returns a function with the right type, but it doesn't
            # look it up through the MRO and so it would defeat polymorphism
            # I don't think python has a built-in thing that does what they lambda does
            # key_func = Book.get_author_sortkey
            key_func = lambda book: book.get_author_sortkey()
        case _:
            raise ValueError("unknown sort type")
    books_list = sorted(library.get_all_books(), key=key_func)
    return render_template("books_list.html.j2", title="All Books", books_list=books_list)

@books.route('/books/<int:accession_id>')
def books_single(accession_id: int):
    book = library.find_book_by_accession_id(accession_id)
    if book is None:
        # 404 error instead?
        raise ValueError("accession_id not found")
    return render_template("books_single.html.j2", title="View Book", book=book)

@books.route('/books', methods=['POST'])
def books_create():
    # form validation
    book_data = {
        'title': request.form['title'],
        'author': request.form['author'],
        'genre': request.form['genre']
    }

    # build object
    new_book = Book(**book_data)
    library.add_new_book(new_book)
    new_accession_id = new_book.accession_id
    return redirect(url_for('.books_single', accession_id = new_accession_id))

@books.route('/books/<int:accession_id>/delete', methods=['POST'])
def books_delete(accession_id: int):
    book = library.find_book_by_accession_id(accession_id)
    if book is None:
        raise ValueError("accession_id not found")
    library.delete_book(book)
    return redirect(url_for('.books_list'))

@books.route('/books/<int:accession_id>/checkoutin', methods=['POST'])
def books_checkoutin(accession_id: int):
    book = library.find_book_by_accession_id(accession_id)
    if book is None:
        raise ValueError("accession_id not found")
    if request.form['direction'] == "in":
        book.check_in()
    elif request.form['direction'] == "out":
        book.check_out()
    else:
        raise ValueError("unknown direction")
    print(request.form['next_page'])
    # if ('next_page' in request.form and
    #         request.form['next_page'] in ['books.books_list', 'books.books_single']):
    #     return redirect(url_for(request.form['next_page'], index=index))
    if 'next_page' in request.form and request.form['next_page'] == 'books.books_single':
        return redirect(url_for('.books_single', accession_id=accession_id))
    else:
        return redirect(url_for('.books_list'))

templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Text">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}{{ title }} — The CodeClan Library{% endblock %}</title>
    {% endblock %}
</head>
<body>
    <header>
    {% block header %}
        <h1>The CodeClan Library</h1>
        {% block subheader %}
        <h2>{{ title }}</h2>
        {% endblock %}
    {% endblock %}
    </header>
{% block content %}
<p>Go to <a href="{{ url_for('books.books_list') }}">all books</a></p>
{% endblock %}
</body>
</html>

templates/books_list.html.j2
{% extends "base.html.j2" %}
{% import "macros.html.j2" as macros %}
{% block content %}

<main>

    <p>Sort by:
        <a href="{{ url_for('.books_list', sort_type='title') }}">title</a>,
        <a href="{{ url_for('.books_list', sort_type='author') }}">author</a>,
        <a href="{{ url_for('.books_list', sort_type='accession_id') }}">accession</a>
    </p>

    <ul class="bookslist">
    {% for book in books_list %}
        <li class="book">
            <span class="details">
                <span class="title">
                    <a href="{{ url_for('.books_single', accession_id=book.accession_id) }}">{{ book.title }}</a>
                </span>
                by <span class="author">{{ book.author }}</span><br>
                — <span class="genre">{{ book.genre }}</span>
                {# {% if book.checked_out %}
                <span class="checked-out">checked out</span>
                {% endif %} #}
            </span>
            <span class="buttons">
                {{ macros.checkoutin_button(book, loop.index0, "inline") }}
            </span>
        </li>
    {% endfor %}
    </ul>

    <form class="create" action="{{ url_for('.books_create') }}"
            method="POST">
        <h3>Create book</h3>
        <div>
            <label for="book_title">Title:</label>
            <input type="text" id="book_title" name="title">
        </div>
        <div>
            <label for="book_author">Author:</label>
            <input type="text" id="book_author" name="author">
        </div>
        <div>
            <label for="book_genre">Genre:</label>
            <select id="book_genre" name="genre">
                <option value="fantasy">Fantasy</option>
                <option value="popular mathematics">Popular Mathematics</option>
                <option value="language &amp; reference">Language &amp; Reference</option>
                <option value="fiction">Fiction</option>
            </select>
        </div>

        <button type="submit">&#x2705; Create Book</button>
    </form>

</main>

{% endblock %}

templates/books_single.html.j2
{% extends "base.html.j2" %}
{% import "macros.html.j2" as macros %}
{% block title %}{{ book.title }} — The CodeClan Library{% endblock %}
{% block subheader %}
<h2>Book details</h2>
{% endblock %}
{% block content %}
<main>
    <div class="booksingle">
        <h3 class="title">{{ book.title }}</h3>
        <h4 class="author">{{ book.author }}</h4>
        <p class="genre">{{ book.genre }}</p>
        {% if book.checked_out %}
        <p class="checked-out">checked out</p>
        {% endif %}
        <div class="actions">
            {{ macros.checkoutin_button(book, index) }}
            {{ macros.delete_button(book, index) }}
            <p>Back to <a href="{{ url_for('.books_list') }}">all books</a></p>
        </div>
    </div>
</main>
{% endblock %}

templates/macros.html.j2
{% macro checkoutin_button(book, index, extraclass='') %}
<form class="checkoutin {{extraclass}}" action="{{ url_for('books.books_checkoutin', accession_id=book.accession_id) }}"
        method="POST">
    {% if book.checked_out %}
    <input type="hidden" name="direction" value="in">
    <input type="hidden" name="next_page" value="{{ request.url_rule.endpoint }}">
    <button type="submit">📕 Check back in</button>
    {% else %}
    <input type="hidden" name="direction" value="out">
    <input type="hidden" name="next_page" value="{{ request.url_rule.endpoint }}">
    <button type="submit">&#x1F4D6; Check out</button>
    {% endif %}
</form>
{% endmacro %}
{% macro delete_button(book, index, extraclass='') %}
<form class="delete {{extraclass}}" action="{{ url_for('books.books_delete', accession_id=book.accession_id) }}"
        method="POST">
    <button type="submit">&#x1F5D1;&#xFE0F; Delete Book</button>
</form>
{% endmacro %}